import type { AgentDefinition } from "../agent-types";

export const agents: AgentDefinition[] = [
  {
    id: "agent-1",
    name: "CodeReviewer Pro",
    description:
      "Reviews code for bugs, security issues, and best practices. Supports Python, TypeScript, and Go with deep static analysis.",
    version: "1.0.0",
    creatorId: "c2",
    creatorName: "Marcus Liu",
    systemPrompt:
      "You are an expert code reviewer. Analyze the provided code for bugs, security vulnerabilities, performance issues, and adherence to best practices. Provide actionable feedback with severity levels.",
    model: "claude-sonnet-4-6",
    temperature: 0.3,
    maxTokens: 4000,
    tools: ["code_analyzer"],
    inputSchema: { type: "text" },
    outputSchema: { type: "json" },
    category: "coding",
    tags: ["code-review", "security", "best-practices"],
    isPublic: true,
    featured: true,
    runs: 12847,
    avgLatencyMs: 3200,
    successRate: 98.5,
    upvotes: 543,
    forks: 89,
    createdAt: "2026-03-15",
    updatedAt: "2026-04-01",
  },
  {
    id: "agent-2",
    name: "DeepResearch",
    description:
      "Multi-source research agent that searches the web, synthesizes findings, and delivers structured reports with citations.",
    version: "2.1.0",
    creatorId: "c3",
    creatorName: "Aiko Tanaka",
    systemPrompt:
      "You are a deep research agent. Given a topic, search multiple sources, cross-reference findings, and produce a comprehensive report with inline citations and confidence scores.",
    model: "claude-opus-4-6",
    temperature: 0.5,
    maxTokens: 8000,
    tools: ["web_search", "doc_reader"],
    inputSchema: { type: "text" },
    outputSchema: { type: "json" },
    category: "research",
    tags: ["research", "citations", "synthesis"],
    isPublic: true,
    featured: true,
    runs: 8432,
    avgLatencyMs: 12500,
    successRate: 96.2,
    upvotes: 721,
    forks: 134,
    createdAt: "2026-02-20",
    updatedAt: "2026-04-03",
  },
  {
    id: "agent-3",
    name: "StoryWeaver",
    description:
      "Creative writing assistant that generates short stories, poetry, and narrative content with adjustable tone and style.",
    version: "1.3.0",
    creatorId: "c4",
    creatorName: "Elena Vasquez",
    systemPrompt:
      "You are a creative writing assistant specializing in short fiction, poetry, and narrative content. Adapt your tone and style based on the user's preferences while maintaining literary quality.",
    model: "claude-sonnet-4-6",
    temperature: 0.8,
    maxTokens: 6000,
    tools: ["style_analyzer"],
    inputSchema: { type: "text" },
    outputSchema: { type: "text" },
    category: "creative",
    tags: ["writing", "fiction", "poetry", "storytelling"],
    isPublic: true,
    featured: false,
    runs: 6219,
    avgLatencyMs: 4800,
    successRate: 97.1,
    upvotes: 389,
    forks: 56,
    createdAt: "2026-03-01",
    updatedAt: "2026-03-28",
  },
  {
    id: "agent-4",
    name: "DataPipeline Builder",
    description:
      "Generates ETL pipelines from natural language descriptions. Supports SQL, Python pandas, and dbt transformations.",
    version: "1.0.2",
    creatorId: "c5",
    creatorName: "Raj Patel",
    systemPrompt:
      "You are a data engineering agent. Convert natural language descriptions into production-ready ETL pipeline code. Support SQL, pandas, and dbt. Include error handling and logging.",
    model: "claude-sonnet-4-6",
    temperature: 0.2,
    maxTokens: 5000,
    tools: ["code_analyzer", "schema_inspector"],
    inputSchema: { type: "text" },
    outputSchema: { type: "json" },
    category: "automation",
    tags: ["data", "ETL", "SQL", "pipeline"],
    isPublic: true,
    featured: false,
    runs: 3854,
    avgLatencyMs: 5600,
    successRate: 94.8,
    upvotes: 267,
    forks: 43,
    createdAt: "2026-03-10",
    updatedAt: "2026-04-02",
  },
  {
    id: "agent-5",
    name: "AlphaSignal",
    description:
      "Analyzes market data, news sentiment, and on-chain metrics to generate trading signals with risk assessments.",
    version: "3.0.1",
    creatorId: "c6",
    creatorName: "Wei Zhang",
    systemPrompt:
      "You are a quantitative trading analyst. Analyze market data, news sentiment, and on-chain metrics. Generate trading signals with confidence levels and risk assessments. Never provide financial advice.",
    model: "claude-opus-4-6",
    temperature: 0.1,
    maxTokens: 4000,
    tools: ["web_search", "data_fetcher"],
    inputSchema: { type: "text" },
    outputSchema: { type: "json" },
    category: "trading",
    tags: ["trading", "signals", "sentiment", "quant"],
    isPublic: true,
    featured: true,
    runs: 15623,
    avgLatencyMs: 8900,
    successRate: 92.3,
    upvotes: 891,
    forks: 201,
    createdAt: "2026-01-28",
    updatedAt: "2026-04-05",
  },
  {
    id: "agent-6",
    name: "StudyBuddy",
    description:
      "Adaptive learning tutor that creates personalized study plans, quizzes, and explanations across STEM subjects.",
    version: "1.2.0",
    creatorId: "c7",
    creatorName: "Priya Sharma",
    systemPrompt:
      "You are an adaptive learning tutor. Assess the student's current level, create personalized study plans, generate practice problems, and provide clear explanations. Adjust difficulty dynamically.",
    model: "claude-sonnet-4-6",
    temperature: 0.4,
    maxTokens: 5000,
    tools: ["quiz_generator"],
    inputSchema: { type: "text" },
    outputSchema: { type: "json" },
    category: "education",
    tags: ["tutoring", "STEM", "adaptive", "quizzes"],
    isPublic: true,
    featured: false,
    runs: 9741,
    avgLatencyMs: 3800,
    successRate: 97.8,
    upvotes: 456,
    forks: 78,
    createdAt: "2026-02-15",
    updatedAt: "2026-04-04",
  },
  {
    id: "agent-7",
    name: "TaskPilot",
    description:
      "Personal productivity assistant that manages tasks, schedules, and reminders with smart prioritization and context awareness.",
    version: "2.0.0",
    creatorId: "c1",
    creatorName: "Sarah Chen",
    systemPrompt:
      "You are a personal productivity assistant. Help users manage tasks, set priorities, create schedules, and stay focused. Use context from past interactions to provide personalized suggestions.",
    model: "claude-haiku-4-5",
    temperature: 0.3,
    maxTokens: 3000,
    tools: ["calendar_api", "reminder_api"],
    inputSchema: { type: "text" },
    outputSchema: { type: "json" },
    category: "assistant",
    tags: ["productivity", "tasks", "scheduling", "GTD"],
    isPublic: true,
    featured: false,
    runs: 21340,
    avgLatencyMs: 1200,
    successRate: 99.1,
    upvotes: 634,
    forks: 112,
    createdAt: "2026-01-10",
    updatedAt: "2026-04-06",
  },
];
