import type { Creator } from "../types";

// ─── Creators ────────────────────────────────────────────────────────────────

export const creators: Creator[] = [
  {
    id: "c1",
    name: "Sarah Chen",
    bio: "NLP researcher turned indie builder. Obsessed with making AI communication feel human.",
    projectCount: 3,
    totalUpvotes: 2140,
    totalPlays: 18200,
    totalRemixes: 24,
    rank: 4,
    weeklyGrowth: 12.5,
    topProjectIds: ["1"],
    joinedAt: "2025-11-15",
    badges: ["pioneer"],
  },
  {
    id: "c2",
    name: "Marcus Liu",
    avatar: "",
    bio: "Serial AI builder. Previously at OpenAI. Building the future of autonomous agents.",
    projectCount: 5,
    totalUpvotes: 4320,
    totalPlays: 38600,
    totalRemixes: 78,
    rank: 1,
    weeklyGrowth: 28.3,
    topProjectIds: ["2", "11"],
    joinedAt: "2025-09-01",
    badges: ["top-creator", "weekly-winner", "viral"],
  },
  {
    id: "c3",
    name: "Yuki Tanaka",
    bio: "Game dev + AI enthusiast from Tokyo. Making creative tools that spark joy.",
    projectCount: 4,
    totalUpvotes: 3210,
    totalPlays: 31400,
    totalRemixes: 65,
    rank: 2,
    weeklyGrowth: 22.1,
    topProjectIds: ["3", "12"],
    joinedAt: "2025-10-20",
    badges: ["top-creator", "remix-king", "viral"],
  },
  {
    id: "c4",
    name: "Alex Rivera",
    avatar: "",
    bio: "Staff engineer by day, vibe coder by night. Building dev tools that actually save time.",
    projectCount: 3,
    totalUpvotes: 2680,
    totalPlays: 22300,
    totalRemixes: 32,
    rank: 3,
    weeklyGrowth: 15.7,
    topProjectIds: ["4", "8"],
    joinedAt: "2025-12-05",
    badges: ["trending"],
  },
  {
    id: "c5",
    name: "Emma Walsh",
    avatar: "",
    bio: "Designer-developer hybrid. Exploring the intersection of AI and creative workflows.",
    projectCount: 2,
    totalUpvotes: 821,
    totalPlays: 7700,
    totalRemixes: 10,
    rank: 7,
    weeklyGrowth: 8.2,
    topProjectIds: ["5", "10"],
    joinedAt: "2026-01-10",
    badges: ["pioneer"],
  },
  {
    id: "c6",
    name: "Jin Park",
    bio: "Voice technology expert. Building accessible AI interfaces for everyone.",
    projectCount: 2,
    totalUpvotes: 890,
    totalPlays: 6200,
    totalRemixes: 8,
    rank: 8,
    weeklyGrowth: 5.4,
    topProjectIds: ["6"],
    joinedAt: "2026-02-01",
    badges: [],
  },
  {
    id: "c7",
    name: "Priya Sharma",
    bio: "Storyteller and AI engineer. Combining narrative design with generative AI.",
    projectCount: 2,
    totalUpvotes: 1450,
    totalPlays: 14800,
    totalRemixes: 30,
    rank: 5,
    weeklyGrowth: 18.9,
    topProjectIds: ["7"],
    joinedAt: "2025-11-28",
    badges: ["trending", "weekly-winner"],
  },
  {
    id: "c8",
    name: "Luna Martinez",
    bio: "Full-stack creator specializing in design-to-code AI. Making frontend magic.",
    projectCount: 2,
    totalUpvotes: 2100,
    totalPlays: 21500,
    totalRemixes: 48,
    rank: 6,
    weeklyGrowth: 34.6,
    topProjectIds: ["9"],
    joinedAt: "2026-01-22",
    badges: ["viral", "weekly-winner"],
  },
];
