import type { Event } from "../types";

// ─── Events ──────────────────────────────────────────────────────────────────

export const events: Event[] = [
  {
    id: "e1",
    title: "VibeCode Global Hackathon 2026",
    type: "hackathon",
    date: "2026-04-20",
    location: "San Francisco + Online",
    organizer: "VibeCode Hunt",
    description:
      "48-hour hackathon to build the most creative AI-native project. $50K in prizes. Open to all skill levels.",
    isOnline: true,
    featured: true,
    image: "",
    aiGeneratedTopics: [
      "Build an AI agent that automates a boring daily task",
      "Create a multiplayer AI game with procedural content",
      "Design an accessibility tool powered by multimodal AI",
      "Remix an existing top project with a unique twist",
    ],
    participantCount: 2400,
    status: "upcoming",
  },
  {
    id: "e2",
    title: "AI Creators Salon: The Future of Vibe Coding",
    type: "salon",
    date: "2026-04-15",
    location: "New York City",
    organizer: "AI Builders Collective",
    description:
      "An intimate evening of demos, discussions, and networking for AI-native creators. Limited to 80 attendees.",
    isOnline: false,
    featured: true,
    aiGeneratedTopics: [
      "How vibe coding changes the builder-user relationship",
      "Monetization strategies for AI-native projects",
      "The remix economy: building on top of others' work",
    ],
    participantCount: 80,
    status: "upcoming",
  },
  {
    id: "e3",
    title: "Demo Day: Top 10 Vibe Projects of Q1",
    type: "demo-day",
    date: "2026-04-12",
    location: "Online (Zoom)",
    organizer: "VibeCode Hunt",
    description:
      "Watch the top 10 projects of Q1 2026 present live. Community voting determines the quarterly champion.",
    isOnline: true,
    featured: true,
    topProjectIds: ["2", "9", "12", "1", "4"],
    aiGeneratedTopics: [
      "What made Q1's top projects stand out",
      "Emerging patterns in AI-native UX",
      "From demo to product: scaling vibe projects",
    ],
    participantCount: 1200,
    status: "upcoming",
  },
  {
    id: "e4",
    title: "Tokyo AI Meetup: Vibe Coding Edition",
    type: "meetup",
    date: "2026-04-18",
    location: "Tokyo, Japan",
    organizer: "Tokyo AI Community",
    description:
      "Monthly meetup focused on vibe coding techniques, tool sharing, and live coding sessions. Bilingual EN/JP.",
    isOnline: false,
    featured: false,
    aiGeneratedTopics: [
      "Live-coding an AI game from scratch",
      "Japanese-language AI tools and NLP challenges",
      "Cross-cultural design patterns for AI products",
    ],
    participantCount: 120,
    status: "upcoming",
  },
  {
    id: "e5",
    title: "AI Agent Building Workshop",
    type: "hackathon",
    date: "2026-04-25",
    location: "London + Online",
    organizer: "European AI Labs",
    description:
      "Hands-on workshop: build and deploy autonomous AI agents in 6 hours. Mentored by industry experts.",
    isOnline: true,
    featured: false,
    aiGeneratedTopics: [
      "Multi-agent orchestration patterns",
      "Tool use and function calling best practices",
      "Testing and debugging autonomous agents",
    ],
    participantCount: 350,
    status: "upcoming",
  },
  {
    id: "e6",
    title: "Shanghai Vibe Coding Night",
    type: "salon",
    date: "2026-03-22",
    location: "Shanghai, China",
    organizer: "Shanghai Dev Hub",
    description:
      "An evening showcasing the best AI projects from Chinese creators. Demos, lightning talks, and networking.",
    isOnline: false,
    featured: false,
    topProjectIds: ["1", "3", "7"],
    aiGeneratedTopics: [
      "AI applications for the Chinese market",
      "Cross-border collaboration in vibe coding",
      "Building bilingual AI products",
      "WeChat mini-program integration with AI tools",
    ],
    participantCount: 95,
    status: "completed",
  },
];
