import type { Project } from "../types";

// ─── Projects ────────────────────────────────────────────────────────────────

export const projects: Project[] = [
  {
    id: "1",
    title: "VibeTranslate",
    tagline: "Real-time AI translation that understands context and emotion",
    description:
      "VibeTranslate goes beyond word-for-word translation. It uses multi-modal AI to capture tone, cultural nuance, and emotional context — then renders translations that actually feel human. Built with Claude 4 and a custom emotion-detection pipeline, it supports 40+ languages with sub-200ms latency. Perfect for global teams, content creators, and anyone tired of robotic translations.",
    category: "AI Tool",
    creatorId: "c1",
    creatorName: "Sarah Chen",
    creatorAvatar: "",
    tags: ["NLP", "Translation", "Real-time", "Multi-modal"],
    thumbnail: "",
    views: 12400,
    upvotes: 847,
    plays: 8920,
    shares: 1340,
    remixCount: 12,
    score: 94,
    behaviorScore: {
      plays: 8920,
      avgStaySeconds: 124,
      shareRate: 0.108,
      remixCount: 12,
      aiScore: 85,
      compound: 8920 * 0.3 + 1340 * 0.25 + 0.108 * 0.2 + 85 * 0.25,
    },
    createdAt: "2026-04-05",
    featured: true,
    demoType: "chat",
    demoUrl: "https://vibetranslate.demo.vibexforge.com",
    demoContent: "Try typing a sentence to see emotion-aware translation in action.",
    viralBoosted: true,
    aiReview: {
      originality: 88,
      clarity: 92,
      uxPotential: 85,
      viralityPotential: 78,
      investorCuriosity: 82,
      strengths: [
        "Emotion-aware translation is a clear differentiator",
        "Sub-200ms latency makes it production-ready",
        "Clean, intuitive interface",
      ],
      weaknesses: [
        "Retention loop unclear after initial wow moment",
        "No collaborative features yet",
      ],
      suggestions: [
        "Add team workspace for shared glossaries",
        "Show emotion breakdown visualization",
        "Create browser extension for inline translation",
      ],
    },
  },
  {
    id: "2",
    title: "AgentForge",
    tagline: "Build autonomous AI agents with drag-and-drop workflows",
    description:
      "AgentForge lets anyone create complex AI agent pipelines without writing code. Connect LLM calls, tool invocations, memory systems, and decision trees through an intuitive visual builder. Export as standalone apps or API endpoints. Already powering 2,000+ agent deployments across startups and enterprises.",
    category: "AI Agent",
    creatorId: "c2",
    creatorName: "Marcus Liu",
    tags: ["Agents", "No-Code", "Automation", "Workflow"],
    thumbnail: "",
    views: 18200,
    upvotes: 1243,
    plays: 14500,
    shares: 2870,
    remixCount: 45,
    score: 97,
    behaviorScore: {
      plays: 14500,
      avgStaySeconds: 167,
      shareRate: 0.142,
      remixCount: 45,
      aiScore: 89.8,
      compound: 14500 * 0.3 + 2870 * 0.25 + 0.142 * 0.2 + 89.8 * 0.25,
    },
    createdAt: "2026-04-04",
    featured: true,
    demoType: "sandbox",
    demoUrl: "https://agentforge.demo.vibexforge.com",
    demoContent: "Drag components to build your first agent in 60 seconds.",
    viralBoosted: true,
    aiReview: {
      originality: 82,
      clarity: 95,
      uxPotential: 93,
      viralityPotential: 88,
      investorCuriosity: 91,
      strengths: [
        "Visual builder dramatically lowers barrier to entry",
        "Export-as-API is a killer feature for developers",
        "Strong community traction already",
      ],
      weaknesses: [
        "Crowded agent-builder space",
        "Debugging complex flows could be challenging",
      ],
      suggestions: [
        "Add agent marketplace for sharing templates",
        "Implement real-time collaboration",
        "Show cost estimation per agent run",
      ],
    },
  },
  {
    id: "3",
    title: "PixelMind",
    tagline: "AI game engine that generates levels from text descriptions",
    description:
      "Describe the game level you want, and PixelMind generates playable 2D environments with physics, enemies, and interactive elements. Uses a fine-tuned diffusion model for assets and an LLM-based level designer for layout and mechanics. Currently supports platformer, puzzle, and RPG genres.",
    category: "AI Game",
    creatorId: "c3",
    creatorName: "Yuki Tanaka",
    tags: ["Gaming", "Generative", "Creative", "Level-Design"],
    thumbnail: "",
    views: 9800,
    upvotes: 672,
    plays: 7200,
    shares: 1560,
    remixCount: 28,
    score: 89,
    behaviorScore: {
      plays: 7200,
      avgStaySeconds: 145,
      shareRate: 0.12,
      remixCount: 28,
      aiScore: 88,
      compound: 7200 * 0.3 + 1560 * 0.25 + 0.12 * 0.2 + 88 * 0.25,
    },
    createdAt: "2026-04-04",
    featured: true,
    demoType: "preview",
    demoUrl: "https://pixelmind.demo.vibexforge.com",
    demoContent: "Type a scene description to generate a playable level.",
    aiReview: {
      originality: 95,
      clarity: 78,
      uxPotential: 88,
      viralityPotential: 92,
      investorCuriosity: 87,
      strengths: [
        "Extremely high novelty — text-to-playable-level is magical",
        "Demo wow factor is off the charts",
        "Strong viral potential on social media",
      ],
      weaknesses: [
        "Limited to 3 genres currently",
        "Asset quality varies significantly",
      ],
      suggestions: [
        "Add multiplayer level sharing",
        "Create a TikTok-style feed of generated levels",
        "Support custom sprite uploads",
      ],
    },
  },
  {
    id: "4",
    title: "CodeReview AI",
    tagline: "Senior engineer-level code reviews powered by multi-agent analysis",
    description:
      "CodeReview AI runs your pull requests through a panel of specialized AI reviewers: security expert, performance optimizer, readability checker, and architecture analyst. Each reviewer provides independent feedback, then a synthesis agent combines insights into actionable, prioritized suggestions. Integrates with GitHub, GitLab, and Bitbucket.",
    category: "AI Workflow",
    creatorId: "c4",
    creatorName: "Alex Rivera",
    tags: ["DevTools", "Code-Review", "Multi-Agent", "CI/CD"],
    thumbnail: "",
    views: 15600,
    upvotes: 1087,
    plays: 11200,
    shares: 1890,
    remixCount: 18,
    score: 93,
    behaviorScore: {
      plays: 11200,
      avgStaySeconds: 132,
      shareRate: 0.098,
      remixCount: 18,
      aiScore: 83.2,
      compound: 11200 * 0.3 + 1890 * 0.25 + 0.098 * 0.2 + 83.2 * 0.25,
    },
    createdAt: "2026-04-03",
    featured: false,
    demoType: "chat",
    demoUrl: "https://codereview-ai.demo.vibexforge.com",
    demoContent: "Paste a code snippet to see multi-perspective AI review.",
    aiReview: {
      originality: 75,
      clarity: 94,
      uxPotential: 90,
      viralityPotential: 72,
      investorCuriosity: 85,
      strengths: [
        "Multi-agent approach gives more thorough reviews than single-model",
        "Git platform integrations make adoption frictionless",
        "Clear value proposition for engineering teams",
      ],
      weaknesses: [
        "Code review AI is a competitive space",
        "Enterprise pricing strategy unclear",
      ],
      suggestions: [
        "Add team-specific coding standards training",
        "Show confidence scores per suggestion",
        "Create VS Code extension for inline reviews",
      ],
    },
  },
  {
    id: "5",
    title: "DreamBoard",
    tagline: "AI-powered mood board generator for designers",
    description:
      "Describe your design vision in natural language and DreamBoard creates curated mood boards with color palettes, typography suggestions, layout references, and AI-generated visual assets. Export directly to Figma. Used by 500+ design teams.",
    category: "AI Tool",
    creatorId: "c5",
    creatorName: "Emma Walsh",
    tags: ["Design", "Creative", "Figma", "Mood-Board"],
    thumbnail: "",
    views: 8900,
    upvotes: 534,
    plays: 5600,
    shares: 870,
    remixCount: 8,
    score: 82,
    behaviorScore: {
      plays: 5600,
      avgStaySeconds: 98,
      shareRate: 0.072,
      remixCount: 8,
      aiScore: 83.6,
      compound: 5600 * 0.3 + 870 * 0.25 + 0.072 * 0.2 + 83.6 * 0.25,
    },
    createdAt: "2026-04-03",
    featured: false,
    demoType: "preview",
    demoUrl: "https://dreamboard.demo.vibexforge.com",
    demoContent: "Describe your aesthetic to generate a mood board.",
    aiReview: {
      originality: 80,
      clarity: 88,
      uxPotential: 91,
      viralityPotential: 85,
      investorCuriosity: 74,
      strengths: [
        "Strong designer workflow integration",
        "Figma export is a smart distribution move",
        "Visual output is highly shareable",
      ],
      weaknesses: [
        "Depends heavily on generated asset quality",
        "Limited customization after generation",
      ],
      suggestions: [
        "Add style mixing from multiple references",
        "Enable real-time collaborative boards",
        "Create Pinterest-style discovery feed",
      ],
    },
  },
  {
    id: "6",
    title: "VoiceOS",
    tagline: "Build voice-first AI apps with one config file",
    description:
      "VoiceOS is a framework for building voice-controlled AI applications. Define your app's capabilities in a YAML config, and VoiceOS handles speech recognition, intent parsing, context management, and response generation. Ships with pre-built modules for smart home, productivity, and accessibility.",
    category: "AI Utility",
    creatorId: "c6",
    creatorName: "Jin Park",
    tags: ["Voice", "Framework", "Accessibility", "SDK"],
    thumbnail: "",
    views: 6700,
    upvotes: 421,
    plays: 3800,
    shares: 520,
    remixCount: 5,
    score: 78,
    behaviorScore: {
      plays: 3800,
      avgStaySeconds: 76,
      shareRate: 0.058,
      remixCount: 5,
      aiScore: 76.6,
      compound: 3800 * 0.3 + 520 * 0.25 + 0.058 * 0.2 + 76.6 * 0.25,
    },
    createdAt: "2026-04-02",
    featured: false,
    demoType: "chat",
    demoUrl: "",
    demoContent: "Try voice commands to see real-time intent parsing.",
    aiReview: {
      originality: 83,
      clarity: 76,
      uxPotential: 80,
      viralityPotential: 65,
      investorCuriosity: 79,
      strengths: [
        "Config-driven approach lowers barrier significantly",
        "Pre-built modules accelerate time-to-market",
        "Strong accessibility angle",
      ],
      weaknesses: [
        "Developer-focused, limited appeal to non-technical users",
        "Documentation could be more beginner-friendly",
      ],
      suggestions: [
        "Add visual flow editor for non-developers",
        "Create showcase gallery of voice apps built with VoiceOS",
        "Partner with accessibility organizations",
      ],
    },
  },
  {
    id: "7",
    title: "NarrativeAI",
    tagline: "Interactive fiction engine powered by adaptive storytelling AI",
    description:
      "NarrativeAI creates branching, adaptive stories that respond to player choices in real-time. Unlike static choice trees, the AI generates new narrative paths dynamically while maintaining plot coherence, character consistency, and emotional arcs. Built for game studios, educators, and creative writers.",
    category: "AI Game",
    creatorId: "c7",
    creatorName: "Priya Sharma",
    tags: ["Storytelling", "Interactive", "Gaming", "Creative"],
    thumbnail: "",
    views: 11300,
    upvotes: 789,
    plays: 8400,
    shares: 1120,
    remixCount: 22,
    score: 86,
    behaviorScore: {
      plays: 8400,
      avgStaySeconds: 156,
      shareRate: 0.094,
      remixCount: 22,
      aiScore: 84.4,
      compound: 8400 * 0.3 + 1120 * 0.25 + 0.094 * 0.2 + 84.4 * 0.25,
    },
    createdAt: "2026-04-02",
    featured: false,
    demoType: "chat",
    demoUrl: "https://narrativeai.demo.vibexforge.com",
    demoContent: "Start an interactive story and make choices to shape the narrative.",
    parentId: "3",
    parentTitle: "PixelMind",
    aiReview: {
      originality: 90,
      clarity: 82,
      uxPotential: 87,
      viralityPotential: 83,
      investorCuriosity: 80,
      strengths: [
        "Dynamic narrative generation is genuinely impressive",
        "Character consistency sets it apart from basic chatbots",
        "Multiple use cases (games, education, writing)",
      ],
      weaknesses: [
        "Story quality can degrade in very long sessions",
        "No multiplayer narrative support yet",
      ],
      suggestions: [
        "Add collaborative storytelling mode",
        "Create story templates marketplace",
        "Implement save/share/fork for story branches",
      ],
    },
  },
  {
    id: "8",
    title: "DataSculpt",
    tagline: "Transform messy data into clean pipelines with natural language",
    description:
      "DataSculpt watches you describe your data transformation needs and builds production-ready ETL pipelines. Upload CSV, JSON, or connect databases — then describe what you want in plain English. It generates, tests, and deploys data pipelines with monitoring and alerting built in.",
    category: "AI Workflow",
    creatorId: "c4",
    creatorName: "Alex Rivera",
    tags: ["Data", "ETL", "Pipeline", "No-Code"],
    thumbnail: "",
    views: 7400,
    upvotes: 498,
    plays: 4300,
    shares: 610,
    remixCount: 7,
    score: 81,
    behaviorScore: {
      plays: 4300,
      avgStaySeconds: 88,
      shareRate: 0.065,
      remixCount: 7,
      aiScore: 80.2,
      compound: 4300 * 0.3 + 610 * 0.25 + 0.065 * 0.2 + 80.2 * 0.25,
    },
    createdAt: "2026-04-01",
    featured: false,
    demoType: "sandbox",
    demoUrl: "",
    demoContent: "Upload sample data and describe your transformation.",
    aiReview: {
      originality: 77,
      clarity: 89,
      uxPotential: 85,
      viralityPotential: 62,
      investorCuriosity: 88,
      strengths: [
        "Solves a real, painful problem for data teams",
        "Natural language interface is well-implemented",
        "Built-in monitoring is a smart differentiator",
      ],
      weaknesses: [
        "Enterprise sales cycle could be long",
        "Complex transformations may need manual SQL fallback",
      ],
      suggestions: [
        "Add pipeline version control and rollback",
        "Create template library for common transformations",
        "Show cost estimation for pipeline runs",
      ],
    },
  },
  {
    id: "9",
    title: "SketchToApp",
    tagline: "Draw UI wireframes and get a working React app instantly",
    description:
      "SketchToApp converts hand-drawn wireframes into functional React components with Tailwind CSS styling. Take a photo of your whiteboard sketch or draw directly in the app — the AI identifies UI elements, infers layout relationships, and generates clean, responsive code. Exports to Next.js, Vite, or standalone React.",
    category: "AI Tool",
    creatorId: "c8",
    creatorName: "Luna Martinez",
    tags: ["UI", "Code-Gen", "Design-to-Code", "React"],
    thumbnail: "",
    views: 21000,
    upvotes: 1456,
    plays: 15200,
    shares: 2950,
    remixCount: 38,
    score: 96,
    behaviorScore: {
      plays: 15200,
      avgStaySeconds: 172,
      shareRate: 0.138,
      remixCount: 38,
      aiScore: 91.4,
      compound: 15200 * 0.3 + 2950 * 0.25 + 0.138 * 0.2 + 91.4 * 0.25,
    },
    createdAt: "2026-04-05",
    featured: true,
    demoType: "preview",
    demoUrl: "https://sketchtoapp.demo.vibexforge.com",
    demoContent: "Upload a sketch to see instant React component generation.",
    viralBoosted: true,
    aiReview: {
      originality: 85,
      clarity: 93,
      uxPotential: 95,
      viralityPotential: 94,
      investorCuriosity: 90,
      strengths: [
        "Sketch-to-code is immediately understandable value prop",
        "Generated code quality is surprisingly high",
        "Multi-framework export maximizes addressable market",
      ],
      weaknesses: [
        "Competing with Figma-to-code tools",
        "Complex layouts still need manual tweaking",
      ],
      suggestions: [
        "Add design system awareness (import existing components)",
        "Create real-time collaborative sketching",
        "Build Figma plugin for bidirectional sync",
      ],
    },
  },
  {
    id: "10",
    title: "EcoTrack AI",
    tagline: "AI sustainability auditor for your codebase and infrastructure",
    description:
      "EcoTrack AI analyzes your code, cloud infrastructure, and CI/CD pipelines to estimate carbon footprint and suggest optimizations. Get real-time sustainability scores, identify wasteful compute patterns, and generate ESG-ready reports. Integrates with AWS, GCP, Azure, and Vercel.",
    category: "Experimental",
    creatorId: "c5",
    creatorName: "Emma Walsh",
    tags: ["Sustainability", "Green-Tech", "DevOps", "Analytics"],
    thumbnail: "",
    views: 4200,
    upvotes: 287,
    plays: 2100,
    shares: 310,
    remixCount: 2,
    score: 73,
    behaviorScore: {
      plays: 2100,
      avgStaySeconds: 54,
      shareRate: 0.042,
      remixCount: 2,
      aiScore: 78.8,
      compound: 2100 * 0.3 + 310 * 0.25 + 0.042 * 0.2 + 78.8 * 0.25,
    },
    createdAt: "2026-04-01",
    featured: false,
    demoType: "sandbox",
    demoUrl: "",
    demoContent: "Connect a repo to see your codebase sustainability score.",
    aiReview: {
      originality: 91,
      clarity: 80,
      uxPotential: 72,
      viralityPotential: 68,
      investorCuriosity: 83,
      strengths: [
        "Unique positioning in sustainability + dev tools",
        "ESG reporting angle opens enterprise doors",
        "Growing regulatory demand for carbon tracking",
      ],
      weaknesses: [
        "Carbon estimation accuracy is hard to validate",
        "Niche audience may limit growth",
      ],
      suggestions: [
        "Add team leaderboards for sustainability goals",
        "Create badges for green-certified repos",
        "Partner with cloud providers for verified metrics",
      ],
    },
  },
  {
    id: "11",
    title: "MeetingMind",
    tagline: "AI meeting copilot that actually remembers your project context",
    description:
      "MeetingMind joins your video calls, transcribes in real-time, and provides context-aware summaries by connecting meeting content to your project management tools. Unlike generic transcription, it understands your team's jargon, ongoing tasks, and decision history.",
    category: "AI Utility",
    creatorId: "c2",
    creatorName: "Marcus Liu",
    tags: ["Meetings", "Productivity", "Transcription", "Context"],
    thumbnail: "",
    views: 13500,
    upvotes: 923,
    plays: 9800,
    shares: 1450,
    remixCount: 14,
    score: 90,
    behaviorScore: {
      plays: 9800,
      avgStaySeconds: 108,
      shareRate: 0.089,
      remixCount: 14,
      aiScore: 80.6,
      compound: 9800 * 0.3 + 1450 * 0.25 + 0.089 * 0.2 + 80.6 * 0.25,
    },
    createdAt: "2026-04-04",
    featured: false,
    demoType: "chat",
    demoUrl: "https://meetingmind.demo.vibexforge.com",
    demoContent: "Simulate a meeting to see context-aware summarization.",
    parentId: "4",
    parentTitle: "CodeReview AI",
    aiReview: {
      originality: 72,
      clarity: 91,
      uxPotential: 88,
      viralityPotential: 70,
      investorCuriosity: 82,
      strengths: [
        "Context-awareness is a genuine differentiator vs Otter/Fireflies",
        "PM tool integration makes it sticky",
        "Clear ROI story for team leads",
      ],
      weaknesses: [
        "Saturated meeting AI market",
        "Privacy concerns with always-on recording",
      ],
      suggestions: [
        "Add action item auto-creation in Jira/Linear",
        "Create meeting health scores",
        "Build async meeting mode for distributed teams",
      ],
    },
  },
  {
    id: "12",
    title: "SynthLab",
    tagline: "AI music production studio in your browser",
    description:
      "SynthLab is a browser-based DAW with AI-powered composition, arrangement, and mixing. Hum a melody, describe a genre, or upload a reference track — the AI generates full arrangements with customizable instruments, effects, and mastering. Export as WAV, MIDI, or stems.",
    category: "Demo",
    creatorId: "c3",
    creatorName: "Yuki Tanaka",
    tags: ["Music", "Creative", "Audio", "Browser"],
    thumbnail: "",
    views: 16800,
    upvotes: 1134,
    plays: 12600,
    shares: 2340,
    remixCount: 31,
    score: 92,
    behaviorScore: {
      plays: 12600,
      avgStaySeconds: 148,
      shareRate: 0.112,
      remixCount: 31,
      aiScore: 88.4,
      compound: 12600 * 0.3 + 2340 * 0.25 + 0.112 * 0.2 + 88.4 * 0.25,
    },
    createdAt: "2026-04-03",
    featured: true,
    demoType: "embedded",
    demoUrl: "https://synthlab.demo.vibexforge.com",
    demoContent: "Describe a mood or hum a melody to generate music.",
    parentId: "3",
    parentTitle: "PixelMind",
    aiReview: {
      originality: 88,
      clarity: 86,
      uxPotential: 92,
      viralityPotential: 91,
      investorCuriosity: 85,
      strengths: [
        "Browser-based removes all friction",
        "Multiple input modes (hum, describe, reference)",
        "Stem export enables professional workflows",
      ],
      weaknesses: [
        "Audio quality inconsistent across genres",
        "Copyright implications for reference-based generation",
      ],
      suggestions: [
        "Add collaborative jam sessions",
        "Create a public library of AI-generated tracks",
        "Integrate with Spotify/SoundCloud for distribution",
      ],
    },
  },
];
