"use client";

import Link from "next/link";
import type { StackPageConfig } from "@/lib/stack-pages";
import { useLang } from "@/lib/i18n";

/**
 * Shared client component that renders one of the 5 vibe-code stack
 * landing pages. Per-stack copy comes from lib/stack-pages.ts; this
 * component is the layout/UI shell.
 *
 * Bilingual: hero/sub stay in English (the source content speaks
 * directly to a tool's audience and English is the lingua franca for
 * Lovable / v0 / Replit / Bolt / Cursor users). Surrounding chrome
 * (CTA, "free during beta", footer) localizes via useLang.
 */
export function StackLanding({ cfg }: { cfg: StackPageConfig }) {
  const { lang } = useLang();
  return (
    <main className="min-h-screen bg-[var(--bg-deep)] text-[var(--text)]">
      {/* Hero */}
      <section className="px-6 pt-24 pb-16 max-w-4xl mx-auto">
        <p
          className="font-pixel text-[10px] uppercase tracking-[0.28em] mb-4"
          style={{ color: cfg.brandColor === "#000000" ? "#F97316" : cfg.brandColor }}
        >
          ▸ FOR{" "}
          <a
            href={cfg.brandUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="underline-offset-2 hover:underline"
          >
            {cfg.brand.toUpperCase()}
          </a>
          {" "}CREATORS
        </p>
        <h1 className="text-3xl sm:text-5xl font-bold leading-tight mb-6 tracking-tight">
          {cfg.hero}
        </h1>
        <p className="text-lg text-foreground/70 max-w-2xl mb-8 leading-relaxed">
          {cfg.subhero}
        </p>
        <div className="flex flex-wrap gap-3 mb-4">
          <Link href="/launch" className="btn-primary btn-primary-lg">
            {lang === "zh"
              ? `提交你的 ${cfg.brand} 项目 →`
              : `Submit your ${cfg.brand} project →`}
          </Link>
          <Link href="/try" className="btn-ghost btn-ghost-lg">
            {lang === "zh" ? "看真实草稿" : "See sample drafts"}
          </Link>
        </div>
        <p className="text-xs text-foreground/40">
          {lang === "zh"
            ? "Beta 期免费 · 不需要信用卡 · URL 例子:"
            : "Free during beta · No credit card · Example URL:"}{" "}
          <code className="text-foreground/60 font-mono">{cfg.urlExample}</code>
        </p>
      </section>

      {/* Pain point */}
      <section className="px-6 py-20 max-w-4xl mx-auto border-t border-white/[0.06]">
        <h2 className="text-2xl font-bold mb-4 tracking-tight">
          {lang === "zh" ? "真实痛点" : "The wall"}
        </h2>
        <p className="text-foreground/75 leading-relaxed text-base">{cfg.pain}</p>
      </section>

      {/* Sample draft preview */}
      <section className="px-6 py-20 max-w-4xl mx-auto border-t border-white/[0.06]">
        <h2 className="text-2xl font-bold mb-2 tracking-tight">
          {lang === "zh"
            ? `${cfg.brand} 项目的草稿大概长这样`
            : `What a draft for a ${cfg.brand} project sounds like`}
        </h2>
        <p className="text-foreground/50 text-sm mb-6">
          {lang === "zh"
            ? "草稿真实由 Claude Sonnet 4.6 生成 —— stack 检测到后,prompt 自动加 stack-aware 提示。"
            : "Drafts are generated by Claude Sonnet 4.6 — when we detect your stack, the prompt is automatically tuned to lead with what matters."}
        </p>
        <div
          className="rounded-lg border-l-4 bg-white/[0.02] p-6"
          style={{ borderLeftColor: cfg.brandColor === "#000000" ? "#F97316" : cfg.brandColor }}
        >
          <p className="text-foreground/90 italic leading-relaxed">
            &ldquo;{cfg.sampleDraftQuote}&rdquo;
          </p>
        </div>
        <p className="text-xs text-foreground/40 mt-4">
          {lang === "zh"
            ? "完整 17 张草稿(X / Reddit / HN / 小红书 / Dev.to / LinkedIn / Bluesky / Threads / 即刻 / Product Hunt)在你 submit 后 10 秒内全部生成。"
            : "Full 17 drafts (X / Reddit / HN / Xiaohongshu / Dev.to / LinkedIn / Bluesky / Threads / Jike / Product Hunt) generated in 10s after you submit."}
        </p>
      </section>

      {/* Stack-aware loop */}
      <section className="px-6 py-20 max-w-4xl mx-auto border-t border-white/[0.06]">
        <h2 className="text-2xl font-bold mb-6 tracking-tight">
          {lang === "zh" ? "怎么用" : "The loop"}
        </h2>
        <ol className="space-y-3">
          {[
            lang === "zh"
              ? `1. 提交你的 ${cfg.brand} 项目 URL(${cfg.urlExample})`
              : `1. Submit your ${cfg.brand} project URL (${cfg.urlExample})`,
            lang === "zh"
              ? "2. VibeX 自动识别 stack,prompt 加 stack-aware 提示"
              : `2. VibeX detects ${cfg.brand}, prompt auto-tuned for the audience`,
            lang === "zh"
              ? "3. 17 张平台原生草稿 ~10 秒内生成"
              : "3. 17 platform-native drafts generated in ~10 seconds",
            lang === "zh"
              ? "4. 审核 / 编辑 / 一键打开平台发布"
              : "4. Review / edit / one-click publish per platform",
            lang === "zh"
              ? "5. 标记已发布并粘贴 URL,我们 6 小时一次抓 engagement"
              : "5. Mark posted + paste URL, we scrape engagement every 6h",
          ].map((step, i) => (
            <li
              key={i}
              className="rounded-md border border-white/[0.06] bg-white/[0.02] p-4 text-sm text-foreground/85"
            >
              {step}
            </li>
          ))}
        </ol>
      </section>

      {/* Bottom CTA */}
      <section className="px-6 py-28 max-w-3xl mx-auto text-center border-t border-white/[0.06]">
        <h2 className="text-2xl sm:text-3xl font-bold mb-4 tracking-tight">
          {lang === "zh"
            ? `给你的 ${cfg.brand} 项目写 17 张草稿,10 秒。`
            : `17 platform-native drafts for your ${cfg.brand} project. 10 seconds.`}
        </h2>
        <p className="text-foreground/60 mb-8 leading-relaxed">
          {lang === "zh"
            ? "Beta 期免费。前 100 名 creator 拿无限次生成 + 公共发现 feed 优先曝光。"
            : "Free during beta. First 100 creators get unlimited generation + priority on the discovery feed."}
        </p>
        <Link href="/launch" className="btn-primary btn-primary-lg">
          {lang === "zh"
            ? `提交你的 ${cfg.brand} 项目 →`
            : `Submit your ${cfg.brand} project →`}
        </Link>
      </section>
    </main>
  );
}
